data:
  task: hallucination
  dataset: scope
  rectify: true
  distill: false
  loader:
    num_workers: 32
    prefetch_factor: 10
  sampler:
    max_batch_size: 128
    max_num_res_squared: 500000
interpolant:
  min_t: 0.01
  twisting:
    use: false
  rots:
    corrupt: true
    sample_schedule: exp
    exp_rate: 10
  trans:
    corrupt: true
    batch_ot: true
    sample_schedule: linear
    sample_temp: 1.0
    vpsde_bmin: 0.1
    vpsde_bmax: 20.0
    potential: null
    potential_t_scaling: false
    rog:
      weight: 10.0
      cutoff: 5.0
  sampling:
    num_timesteps: 100
    do_sde: false
  self_condition: ${model.edge_features.self_condition}
experiment:
  is_training: true
  debug: false
  seed: 123
  num_devices: 4
  warm_start: null
  warm_start_cfg_override: true
  resume_cfg_path: null
  resume_ckpt_path: null
  resume: false
  training:
    mask_plddt: true
    bb_atom_scale: 0.1
    trans_scale: 0.1
    translation_loss_weight: 2.0
    t_normalize_clip: 0.9
    rotation_loss_weights: 1.0
    aux_loss_weight: 1.0
    aux_loss_use_bb_loss: true
    aux_loss_use_pair_loss: true
    aux_loss_t_pass: 0.25
  wandb:
    name: null
    project: null
  optimizer:
    lr: 0.0001
  trainer:
    overfit_batches: 0
    min_epochs: 1
    max_epochs: 1000
    accelerator: gpu
    log_every_n_steps: 1
    deterministic: false
    strategy: ddp
    check_val_every_n_epoch: 1
    accumulate_grad_batches: 2
  checkpointer:
    dirpath: null
    save_last: true
    save_top_k: -1
  inference_dir: null
shared:
  seed: 123
  max_cache_size: 100000
  min_motif_percent: 0.05
  max_motif_percent: 0.5
scope_dataset:
  seed: ${shared.seed}
  csv_path: null
  rectify_csv_path: null
  max_cache_size: ${shared.max_cache_size}
  cache_num_res: 0
  add_plddt_mask: false
  min_eval_length: 60
  max_eval_length: 128
  inpainting_percent: 1.0
  samples_per_eval_length: 10
  num_eval_lengths: 10
  filter:
    max_num_res: 128
    min_num_res: 60
    max_coil_percent: 0.5
    rog_quantile: 0.96
    oligomeric:
    - monomeric
    num_chains:
    - 1
  min_motif_percent: ${shared.min_motif_percent}
  max_motif_percent: ${shared.max_motif_percent}
pdb_dataset:
  seed: ${shared.seed}
  csv_path: null
  cluster_path: ./metadata/pdb.clusters
  max_cache_size: ${shared.max_cache_size}
  cache_num_res: 0
  inpainting_percent: 1.0
  add_plddt_mask: false
  min_eval_length: 100
  max_eval_length: 300
  samples_per_eval_length: 10
  num_eval_lengths: 10
  filter:
    max_num_res: 512
    min_num_res: 60
    max_coil_percent: 0.5
    rog_quantile: 0.96
    oligomeric:
    - monomeric
    num_chains:
    - 1
  min_motif_percent: ${shared.min_motif_percent}
  max_motif_percent: ${shared.max_motif_percent}
model:
  node_embed_size: 256
  edge_embed_size: 128
  symmetric: false
  node_features:
    c_s: ${model.node_embed_size}
    c_pos_emb: 128
    c_timestep_emb: 128
    max_num_res: 2000
    timestep_int: 1000
    embed_chain: false
  edge_features:
    single_bias_transition_n: 2
    c_s: ${model.node_embed_size}
    c_p: ${model.edge_embed_size}
    relpos_k: 64
    feat_dim: 64
    num_bins: 22
    self_condition: true
    embed_chain: false
    embed_diffuse_mask: true
    use_rbf: true
    num_rbf: 32
  ipa:
    c_s: ${model.node_embed_size}
    c_z: ${model.edge_embed_size}
    c_hidden: 128
    no_heads: 8
    no_qk_points: 8
    no_v_points: 12
    seq_tfmr_num_heads: 4
    seq_tfmr_num_layers: 2
    num_blocks: 6
